---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    labels:
{{ include "grafana.labels.stakater" . | indent 6 }}
{{ include "grafana.labels.chart" . | indent 6 }}
    name: {{ template "grafana.name" . }}-dashboards
  data:
{{- range $key, $value := .Values.grafana.configFiles }}
    {{ $key }}: |
{{ $value | indent 6 }}
{{- end }}
