apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
{{ include "labels.stakater" . | indent 4 }}
{{ include "labels.chart" . | indent 4 }}
  annotations:
    configmap.fabric8.io/update-on-change: {{ template "name" . }}-dashboards
  name: {{ template "name" . }}
spec:
  replicas: {{ .Values.grafana.deployment.replicas }}
  template:
    metadata:
      labels:
{{ include "labels.selector" . | indent 8 }}
    spec:
      containers:
      - name: {{ template "name" . }}
        image: "{{ .Values.grafana.deployment.image.name }}:{{ .Values.grafana.deployment.image.tag }}"
        env:
        - name: GF_AUTH_BASIC_ENABLED
          value: "{{ .Values.grafana.deployment.environment.basicAuthEnabled }}"
        - name: GF_SERVER_ROOT_URL
          value: "{{ .Values.grafana.deployment.environment.serverRootUrl }}"
        - name: GF_AUTH_PROXY_ENABLED
          value: "{{ .Values.grafana.deployment.environment.authProxyEnabled }}"
        - name: GF_AUTH_PROXY_HEADER_NAME
          value: "{{ .Values.grafana.deployment.environment.authProxyHeaderName }}"
        - name: GF_AUTH_PROXY_HEADER_PROPERTY
          value: "{{ .Values.grafana.deployment.environment.authProxyHeaderProperty }}"
        - name: GF_AUTH_DISABLE_LOGIN_FORM
          value: "{{ .Values.grafana.deployment.environment.authDisableLoginForm }}"
        - name: GF_SECURITY_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: {{ template "name" . }}-credentials
              key: user
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "name" . }}-credentials
              key: password
        volumeMounts:
        - name: {{ template "name" . }}-storage
          mountPath: /var/{{ template "name" . }}-storage
        - name: {{ template "name" . }}-persistent-storage
          mountPath: /var/lib/{{ template "name" . }}
        ports:
        - name: {{ .Values.grafana.deployment.environment.ports.name }}
          containerPort: {{ .Values.grafana.deployment.environment.ports.containerPort }}
        {{- with .Values.grafana.resources }}
        resources:
          {{- with .requests }}
          requests:
            {{- with .memory }}
            memory: {{ . }}
            {{- end }}
            {{- with .cpu }}
            cpu: {{ . }}
            {{- end }}
          {{- end }}
          {{- with .limits }}
          limits:
            {{- with .memory }}
            memory: {{ . }}
            {{- end }}
            {{- with .cpu }}
            cpu: {{ . }}
            {{- end }}
          {{- end }}
        {{- end }}
      - name: {{ template "name" . }}-watcher
        image: "{{ .Values.grafana.deployment.watcher.image.name }}:{{ .Values.grafana.deployment.watcher.image.tag }}"
        args:
          - '--watch-dir={{ .Values.grafana.deployment.watcher.args.watcherDir }}'
          - '--{{ template "name" . }}-url={{ .Values.grafana.deployment.watcher.args.watcherUrl }}'
        env:
        - name: GRAFANA_USER
          valueFrom:
            secretKeyRef:
              name: {{ template "name" . }}-credentials
              key: user
        - name: GRAFANA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "name" . }}-credentials
              key: password
        {{- with .Values.grafana.watcherResources }}
        resources:
          {{- with .requests }}
          requests:
            {{- with .memory }}
            memory: "{{ . }}"
            {{- end }}
            {{- with .cpu }}
            cpu: "{{ . }}"
            {{- end }}
          {{- end }}
          {{- with .limits }}
          limits:
            {{- with .memory }}
            memory: "{{ . }}"
            {{- end }}
            {{- with .cpu }}
            cpu: "{{ . }}"
            {{- end }}
          {{- end }}
        {{- end }}
        volumeMounts:
        - name: {{ template "name" . }}-dashboards
          mountPath: /var/{{ template "name" . }}-dashboards
      - name: proxy
        image: "{{ .Values.grafana.deployment.proxy.image.name }}:{{ .Values.grafana.deployment.proxy.image.tag }}"
        args:
          - --config={{ .Values.grafana.deployment.proxy.args.configFile }}
          - --upstream-url={{ .Values.grafana.deployment.proxy.args.upstreamUrl }}
          - --enable-authorization-header={{ .Values.grafana.deployment.proxy.args.enableAuthorization }}
          - --redirection-url={{ .Values.grafana.deployment.proxy.args.redirectionUrl }}
        volumeMounts:
        - name: keycloak-proxy-config
          mountPath: /etc/config
      nodeSelector:
        failure-domain.beta.kubernetes.io/zone: us-west-2a
      volumes:
      - name: {{ template "name" . }}-storage
        emptyDir: {}
      - name: {{ template "name" . }}-persistent-storage
        persistentVolumeClaim:
          claimName: {{ .Values.grafana.deployment.persistantVolumeName }}
      - name: {{ template "name" . }}-dashboards
        configMap:
          name: {{ template "name" . }}-dashboards
      - name: keycloak-proxy-config
        configMap:
          name: keycloak-proxy
