apiVersion: v1
kind: Secret
metadata:
  labels:
{{ include "grafana.labels.stakater" . | indent 4 }}
{{ include "grafana.labels.chart" . | indent 4 }}
  name: {{ template "grafana.name" . }}-credentials
data:
  user: {{ .Values.grafana.secret.user }}
  password: {{ .Values.grafana.secret.password }}
