apiVersion: v1
kind: Secret
metadata:
  labels:
{{ include "grafana.labels.stakater" . | indent 4 }}
{{ include "grafana.labels.chart" . | indent 4 }}
  name: {{ template "grafana.name" . }}-credentials
data:
  user: {{ .Values.grafana.secrets.user }}
  password: {{ .Values.grafana.secrets.password }}
---
apiVersion: v1
data:
  grafana.ini: {{ .Values.grafana.config }}
kind: Secret
metadata:
  name: {{ template "grafana.name" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "grafana.labels.stakater" . | indent 4 }}
{{ include "grafana.labels.chart" . | indent 4 }}
type: Opaque