apiVersion: v1
kind: Service
metadata:
  name: {{ template "grafana.name" . }}
  labels:
    expose: "{{ .Values.grafana.service.expose }}"
{{ include "grafana.labels.stakater" . | indent 4 }}
{{ include "grafana.labels.chart" . | indent 4 }}
{{- if .Values.grafana.service.annotations }}
  annotations:
{{ toYaml .Values.grafana.service.annotations | indent 4 }}
{{- end }}
spec:
  ports:
  - port: 80
    protocol: TCP
{{- if .Values.grafana.deployment.proxy.enabled }}
    targetPort: 80
{{- else }}
    targetPort: {{ .Values.grafana.deployment.environment.ports.containerPort }}
{{- end }}
  selector:
{{ include "grafana.labels.selector" . | indent 4 }}
