apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}
  labels:
    expose: "{{ .Values.grafana.service.expose }}"
{{ include "labels.stakater" . | indent 4 }}
{{ include "labels.chart" . | indent 4 }}
  annotations:
    fabric8.io/ingress.path: {{ .Values.grafana.service.ingressPath }}
    fabric8.io/ingress.annotations: |-
      ingress.kubernetes.io/rewrite-target: {{ .Values.grafana.service.rewriteTarget }}
      ingress.kubernetes.io/force-ssl-redirect: {{ .Values.grafana.service.forceSslRedirect }}
      kubernetes.io/ingress.class: {{ .Values.grafana.service.ingressClass }}
      {{- with .Values.grafana.service.annotations }}
      {{- range $key, $value := . }}
      {{ $key }}: {{ $value }}
      {{- end }}
      {{- end }}
spec:
  ports:
  - port: 80
    protocol: TCP
{{- if .Values.grafana.deployment.proxy.enabled }}
    targetPort: 80
{{- else }}
    targetPort: {{ .Values.grafana.deployment.environment.ports.containerPort }}
{{- end }}
  selector:
{{ include "labels.selector" . | indent 4 }}
