kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
{{ include "grafana-storage.labels.stakater" . | indent 4 }}
{{ include "grafana-storage.labels.chart" . | indent 4 }}
  name: {{ .Values.grafanaStorage.pvcName }}
spec:
  accessModes:
    - {{ .Values.grafanaStorage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.grafanaStorage.capacity }}
  storageClassName: {{ .Values.grafanaStorage.storageClassName }}
