grafana:
  labels:
    group: com.stakater.provider
    provider: stakater
    version: 4.6.3
  namespace: dev
  deployment:
    image:
      name: grafana/grafana
      tag: "4.6.3"
    environment:
      ports:
        name: web
        containerPort: 1234
      resources:
        requests:
          memory: 100Mi
          cpu: 100m
        limits:
          memory: 200Mi
          cpu: 200m
    watcher:
      config:
        image:
          name: quay.io/coreos/grafana-watcher
          tag: v0.0.8
        args:
          watcherDir: dummy
          watcherUrl: dummy
        resources:
          limits:
            cpu: 100m
            memory: 32Mi
          requests:
            cpu: 50m
            memory: 16Mi
    proxy:
      config:
        image:
          name: quay.io/gambol99/keycloak-proxy
          tag: v2.1.1
        args:
          configFile: dummy
          upstreamUrl: dummy
          enableAuthorization: --enable-authorization-header=false
          redirectionUrl: dummy
        volumeMounts:
          name: keycloak-proxy-config
          mountPath: /etc/config
  secret:
    config:
      user: dummy
      password: dummy
  service:
    expose: true
    annotations: |-
      ingress.kubernetes.io/rewrite-target: /
      ingress.kubernetes.io/force-ssl-redirect: false
      kubernetes.io/ingress.class: internal-ingress
    spec:
      ports:
        port: 80
        protocol: TCP
        targetPort: 80
  configFiles:
