global:
  image:
    registry:

grafana:
  config: W2F1dGguYmFzaWNdCmVuYWJsZWQgPSBmYWxzZQpbYXV0aC5hbm9ueW1vdXNdCmVuYWJsZWQgPSB0cnVlCm9yZ19yb2xlID0gRWRpdG9yCg==  
  labels:
    group: com.stakater.platform
    provider: stakater
    version: 5.2.1
  forecastle: {}
    # icon: https://cdn-images-1.medium.com/max/521/0*D__TQ7qMdoq3Y7kP.png
    # expose: "true"
  annotations: 
    configmapReloader: grafana-dashboards
    secretReloader: grafana-credentials,grafana-config
  deployment:
    clearSecurityContext: false
    replicas: 1
    # nodeSelector:
    #   key: failure-domain.beta.kubernetes.io/zone
    #   value: us-west-2a    
    container: 
      clearSecurityContext: false
    image:
      name: grafana/grafana
      tag: "5.2.1"
    environment:
      basicAuthEnabled: "true"
      serverRootUrl: http://localhost:3000
      path: /grafana
      authProxyEnabled: "true"
      authProxyHeaderName: "X-Auth-Email"
      authProxyHeaderProperty: email
      authDisableLoginForm: "true"
      authAnonymousEnable: "false"
      authAnonymousRole: "Admin"
      ports:
        name: web
        containerPort: 3000
    watcher:
      enabled: true
      image:
        name: quay.io/coreos/grafana-watcher
        tag: v0.0.8
      args:
        watcherDir: /var/grafana-dashboards        
    proxy:
      enabled: true
      image:
        name: quay.io/gambol99/keycloak-proxy
        tag: v2.1.1
      args:
        configFile: /etc/config/config.yml
        upstreamUrl: http://127.0.0.1:3000
        enableAuthorization: "false"
        redirectionUrl: /grafana
    persistantVolumeName: grafana-persistent-storage
    configmapWatcher:
      image:
        registry:
        name: kiwigrid/k8s-sidecar
        tag: "0.0.6"
        pullPolicy:
      datasources:
        enabled: false
      dashboards:
        enabled: false
      
  # resources:
  #   requests:
  #     memory: 100Mi
  #     cpu: 100m
  #   limits:
  #     memory: 200Mi
  #     cpu: 200m
  # watcherResources:
  #   limits:
  #     cpu: 100m
  #     memory: 32Mi
  #   requests:
  #     cpu: 50m
  #     memory: 16Mi
  secrets:
    user: ""
    password: ""
  service:
    expose: "true"
    annotations: {}
# Add these under xposer.stakater.com/annotations
# forecastle.stakater.com/expose: true
# forecastle.stakater.com/icon: https://cdn-images-1.medium.com/max/521/0*D__TQ7qMdoq3Y7kP.png
  shouldUseGenericUrl: false     # if true, use the init-container to replace the values in the configmaps
  configFiles:         
  datasources:
    additionalDataSourceDefs: {}
    includeDefaults: true
    prometheusDatasourceUrl: http://prometheus
    watcher:
      folder: /tmp/datasources
      label: grafana.datasource.test
      namespace:
  dashboards:
    watcher:
      folder: /tmp/dashboards
      label: grafana.dashboard.test
      namespace: