grafana:
  labels:
    group: com.stakater.platform
    provider: stakater
    version: 4.6.3
  namespace: dev
  deployment:
    image:
      name: grafana/grafana
      tag: "4.6.3"
    environment:
      ports:
        name: web
        containerPort: 1234
      resources:
        requests:
          memory: 123Mi
          cpu: 123m
        limits:
          memory: 123Mi
          cpu: 123m
    watcher:
      image:
        name: quay.io/coreos/grafana-watcher
        tag: v0.0.8
      args:
        watcherDir: dummy
        watcherUrl: dummy
      resources:
        limits:
          cpu: 100m
          memory: 32Mi
        requests:
          cpu: 50m
          memory: 16Mi
    proxy:
      image:
        name: dummy
        tag: v2.1.1
      args:
        configFile: dummy
        upstreamUrl: dummy
        enableAuthorization: "false"
        redirectionUrl: dummy
      volumeMounts:
        name: keycloak-proxy-config
        mountPath: /etc/config
  secret:
    user: dummy
    password: dummy
  service:
    expose: true
    ingressPath: /grafana
    rewriteTarget: /
    forceSslRedirect: "false"
    ingressClass: internal-ingress
    annotations:
  configFiles:
