grafana:
  labels:
    group: com.stakater.platform
    provider: stakater
    version: 5.0.4
  forecastle: {}
    # icon: https://cdn-images-1.medium.com/max/521/0*D__TQ7qMdoq3Y7kP.png
    # expose: "true"
  annotations: 
    configmapFabric8ioUpdateOnChange: grafana-dashboards
  deployment:
    clearSecurityContext: false
    replicas: 1
    # nodeSelector:
    #   key: failure-domain.beta.kubernetes.io/zone
    #   value: us-west-2a    
    image:
      name: grafana/grafana
      tag: "5.0.4"
    environment:
      basicAuthEnabled: "true"
      serverRootUrl: http://localhost:3000
      path: /grafana
      authProxyEnabled: "true"
      authProxyHeaderName: "X-Auth-Email"
      authProxyHeaderProperty: email
      authDisableLoginForm: "true"
      ports:
        name: web
        containerPort: 3000
    watcher:
      image:
        name: quay.io/coreos/grafana-watcher
        tag: v0.0.8
      args:
        watcherDir: /var/grafana-dashboards        
    proxy:
      enabled: true
      image:
        name: quay.io/gambol99/keycloak-proxy
        tag: v2.1.1
      args:
        configFile: /etc/config/config.yml
        upstreamUrl: http://127.0.0.1:3000
        enableAuthorization: "false"
        redirectionUrl: /grafana
    persistantVolumeName: grafana-persistent-storage
  # resources:
  #   requests:
  #     memory: 100Mi
  #     cpu: 100m
  #   limits:
  #     memory: 200Mi
  #     cpu: 200m
  # watcherResources:
  #   limits:
  #     cpu: 100m
  #     memory: 32Mi
  #   requests:
  #     cpu: 50m
  #     memory: 16Mi
  secrets:
    user: dummy
    password: dummy
  service:
    expose: "true"
    ingressPath: /grafana
    rewriteTarget: /
    forceSslRedirect: "false"
    ingressClass: internal-ingress
    annotations:
  shouldUseGenericUrl: false     # if true, use the init-container to replace the values in the configmaps
  configFiles:
