grafana:
  labels:
    group: com.stakater.platform
    provider: stakater
    version: 4.6.3
  annotations: 
    configmapFabric8ioUpdateOnChange: grafana-dashboards
  namespace: dev
  deployment:
    replicas: 1
    zone: eu-west-1a
    image:
      name: grafana/grafana
      tag: "4.6.3"
    environment:
      basicAuthEnabled: "true"
      serverRootUrl: http://localhost:3000/grafana/
      authProxyEnabled: "true"
      authProxyHeaderName: "X-Auth-Email"
      authProxyHeaderProperty: email
      authDisableLoginForm: "true"
      ports:
        name: web
        containerPort: 3000
    watcher:
      image:
        name: quay.io/coreos/grafana-watcher
        tag: v0.0.8
      args:
        watcherDir: /var/grafana-dashboards
        watcherUrl: http://localhost:3000
    proxy:
      enabled: true
      image:
        name: quay.io/gambol99/keycloak-proxy
        tag: v2.1.1
      args:
        configFile: /etc/config/config.yml
        upstreamUrl: http://127.0.0.1:3000
        enableAuthorization: "false"
        redirectionUrl: /grafana
    persistantVolumeName: grafana-persistent-storage
  # resources:
  #   requests:
  #     memory: 100Mi
  #     cpu: 100m
  #   limits:
  #     memory: 200Mi
  #     cpu: 200m
  # watcherResources:
  #   limits:
  #     cpu: 100m
  #     memory: 32Mi
  #   requests:
  #     cpu: 50m
  #     memory: 16Mi
  secret:
    user: dummy
    password: dummy
  service:
    expose: "true"
    ingressPath: /grafana
    rewriteTarget: /
    forceSslRedirect: "false"
    ingressClass: internal-ingress
    annotations:
  configFiles:
